copy Ticket_Sales_Project.exe accountsexist /Y
copy Ticket_Sales_Project.exe accountType1 /Y
copy Ticket_Sales_Project.exe accountType2 /Y
copy Ticket_Sales_Project.exe accountType3 /Y
copy Ticket_Sales_Project.exe accountType4 /Y
copy Ticket_Sales_Project.exe adminCreate /Y
copy Ticket_Sales_Project.exe creditAdmin /Y
copy Ticket_Sales_Project.exe creditNonAdmin /Y
copy Ticket_Sales_Project.exe credit1000 /Y
copy Ticket_Sales_Project.exe currentaccount /Y
copy Ticket_Sales_Project.exe deletable /Y
copy Ticket_Sales_Project.exe invalidbuy /Y
copy Ticket_Sales_Project.exe invalidcredit /Y
copy Ticket_Sales_Project.exe invalidrefund /Y
copy Ticket_Sales_Project.exe invalidsell /Y
copy Ticket_Sales_Project.exe maxTickets /Y
copy Ticket_Sales_Project.exe noshow /Y
copy Ticket_Sales_Project.exe numberMax /Y
copy Ticket_Sales_Project.exe refundable /Y
copy Ticket_Sales_Project.exe refundNoOverflow /Y
copy Ticket_Sales_Project.exe sellable /Y
copy Ticket_Sales_Project.exe sellerhascredit /Y
copy Ticket_Sales_Project.exe sellMax /Y
copy Ticket_Sales_Project.exe Testshow1 /Y
copy Ticket_Sales_Project.exe titleMax /Y
copy Ticket_Sales_Project.exe uniqueUser /Y
copy Ticket_Sales_Project.exe user1 /Y
copy Ticket_Sales_Project.exe username15 /Y
copy Ticket_Sales_Project.exe userNotExist /Y
copy Ticket_Sales_Project.exe userType /Y